### ISSUE TITLE
Purifier Block

### ISSUE THREAD

**Issue by MyWorldNetwork** [Caltinor/Corrupted-Land#7]
A passive, beacon-like, Purifier block which could be fed either by the sun, a solid fuel, or even some form of electricity (not my preferred option personally as I don't any means of making electricity in my mod pack) and which has a radius to keep corruption at bay

**Comment by Caltinor** [comment]
I am open sourcing this mod and discontinuing development on it personally.  This can be added by another dev willing to continue the mod.
